### PR TITLE
Allow webhosting overwrite

### PR DESCRIPTION
**Pull request by vepasto**

### CODE REVIEW

**Comment by jpillora** [comment]
Currently it seems that websites enabled if they dont exist

``` js
if(err && err.name === 'NoSuchWebsiteConfiguration')
```

Will overwriting by default cause any harm?

**Comment by vepasto** [comment]
WebHosting settings will not be overwritten by default, because `allowWebHostingOverWrite` is set `false` by default

DEFAULTS: 
`allowWebHostingOverWrite: false`

`if ((err && err.name === 'NoSuchWebsiteConfiguration') || opts.allowWebHostingOverWrite)`

I'm using this overwrite in my current application and I don't see any harm this could cause.

**Comment by jpillora** [comment]
Sorry I should have clarified, *instead of this PR* can we have no option, and when `enableWeb` is on - it's always overwritten?

**Comment by vepasto** [comment]
Users may have changed options by S3 console and those changes will then be overwritten.

**Comment by vepasto** [comment]
We could make that change if we add **major** version?

**Comment by jpillora** [comment]
hmmm maybe instead well add this to the `enableWeb` option:
* `falsy` off
* `truthy` on - no overwrite
* `"force"` on - overwrite

This just saves adding another option for something that maybe not many will use, sound ok?

**Comment by vepasto** [comment]
currently my `enableWeb` is an object containing custom settings:

```
enableWeb: {
  <my-own-settings-here>
}
```

so `"force"` wont allow this

**Comment by jpillora** [comment]
Your [enableWeb](https://github.com/vepasto/grunt-aws/blob/web-hosting-overwrite/tasks/services/s3.js#L29) ? An object would also work, falsy, truthy and object with "sub-settings" (which would also be truthy). Then inside there you could an `overwrite` option?

**Comment by vepasto** [comment]
This object is directly sent to _aws s3_, so I would not pollute it with own properties.

**Comment by vepasto** [comment]
We could add there some kind of _prefix_ to make sure we are not accidentally using `S3` properties

**Comment by jpillora** [comment]
Ah I see, an object is already used, sorry missed that. I think a prefixed property would be fine, like `grunt-overwrite`.

**Comment by vepasto** [comment]
Yees! I'll do that!

**Comment by vepasto** [comment]
@jpillora, please check new commit

**Comment by vepasto** [comment]
Sorry about pushing incomplete code! But now it works!

**Comment by jpillora** [comment]
thanks @vepasto sorry for the delay

**Pull request merged**
