### PR TITLE
Make cloudfront task a multi-task...

### PR DESCRIPTION
**Pull request by woodcoder**
...so that different groups of paths to be invalidated can be specified.

### CODE REVIEW

**Comment by npaton** [comment]
This has been tested and is good to go. Merge +1

**Comment by jpillora** [comment]
Sorry guys, will push now

**Comment by jpillora** [comment]
https://npmjs.org/package/grunt-aws is now at `0.4.1`

**Comment by EgoAleSum** [comment]
Thanks for this fix. However, next time, PLEASE, before bumping the version ensure that you REMEMBER ABOUT [SEMVER](http://semver.org/).

I've spent 2 hours trying to figure out why my deploy system wasn't pushing invalidations to CloudFront... A backwards-incompatible change should have not been pushed in a patch revision.

**Comment by jpillora** [comment]
Oh sorry, totally forgot this wouldnt be backwards compatible, will
unpublish and republish 0.5

Definitely need a maintainer for this project, haven't used it in 3 years
lol

**Comment by jpillora** [comment]
Published old version at 0.4.2 (unpublish didnt work for some reason), and this version is now 0.5.0, does npm understands the 0.x.y section of the semvar spec?

**Pull request merged**
