### PR TITLE
Fix exception on trying to access mime.lookup

### PR DESCRIPTION
**Pull request by rchl**
Revert back to v1 of mime dependency as v2 has breaking changes and
code wasn't updated.

### CODE REVIEW

**Comment by rchl** [comment]
Fixes #68

**Comment by jpillora** [comment]
Thanks for the PR, before we merge, can you test with the new API: https://github.com/jpillora/grunt-aws/issues/68#issuecomment-466516006 ?

**Comment by rchl** [comment]
I've looked into that before making PR but I've decided not to migrate code to new API as it seemed not trivial and I wanted fix to be as safe as possible.

The part that was not trivial was use of `mime.charsets.lookup()`* in current code which doesn't even seem to be available in v2.

I just didn't want to refactor that and risk regressions.

* https://www.npmjs.com/package/mime/v/1.6.0

**Comment by rchl** [comment]
Thank you for quick merging. :)

**Pull request merged**
