### PR TITLE
Additional Cloudfront operations

### PR DESCRIPTION
**Pull request by jrit**
@jpillora added a few more cloudfront operations. Please see readme updates for an explanation. I'm attempting to balance the need to inject a ton of configuration and the need to actually update that configuration, since most of it probably doesn't change often for most users. I added a patch version increment as well, maybe it should be a minor though?

### CODE REVIEW

**Comment by jpillora** [comment]
Hi @jrit thanks for the PR, I don't actually use the CF module so I'm not sure - is this backwards compatible?

**Comment by jrit** [comment]
It is backwards compatible. Previously there was only an option for invalidations, this just adds some more options.

**Comment by jpillora** [comment]
cool thanks - merged, will publish soon

**Comment by jpillora** [comment]
published, sorry for the delay

**Pull request merged**
